import {
  pgTable,
  text,
  timestamp,
  integer,
  boolean,
  jsonb,
  uuid,
} from "drizzle-orm/pg-core";
export const profiles = pgTable("learner_profiles", {
  userId: text("user_id").primaryKey(),
  interests: jsonb("interests").$type<string[]>().default([]),
  goal: text("goal").default("Explicar um bloqueio sem roteiro"),
  weeklyGoal: integer("weekly_goal").default(5),
  sessionMinutes: integer("session_minutes").default(25),
  difficulty: text("difficulty").default("A2"),
  locale: text("locale").default("pt-BR"),
  timezone: text("timezone").default("America/Sao_Paulo"),
  englishVariant: text("english_variant").default("en-US"),
  theme: text("theme").default("system"),
  onboarded: boolean("onboarded").default(false),
  diagnostic: jsonb("diagnostic").default({}),
  shortcutsEnabled: boolean("shortcuts_enabled").default(true),
  monthlyLimitCents: integer("monthly_limit_cents").default(4000),
  alertCents: integer("alert_cents").default(2500),
});
export const sources = pgTable("sources", {
  id: uuid("id").primaryKey().defaultRandom(),
  userId: text("user_id").notNull(),
  kind: text("kind").notNull(),
  title: text("title").notNull(),
  author: text("author").notNull(),
  language: text("language").notNull(),
  url: text("url"),
  videoId: text("video_id"),
  rights: text("rights").notNull(),
  status: text("status").notNull(),
  isExample: boolean("is_example").default(false),
  revision: integer("revision").default(1),
  durationMs: integer("duration_ms"),
  positionMs: integer("position_ms").default(0),
  fileKey: text("file_key"),
  metadataUpdatedAt: timestamp("metadata_updated_at", { withTimezone: true }),
  transcriptionMode: text("transcription_mode").default("manual"),
  transcriptProvider: text("transcript_provider"),
  transcriptModel: text("transcript_model"),
  transcriptReviewed: boolean("transcript_reviewed").default(false),
  transcriptionRequestedAt: timestamp("transcription_requested_at", {
    withTimezone: true,
  }),
  transcriptionCompletedAt: timestamp("transcription_completed_at", {
    withTimezone: true,
  }),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow(),
});
